### ISSUE TITLE
Windows: pts/renaissance-1.1.1: Test: Scala Dotty fails; debug-benchmark output included

### ISSUE THREAD

**Issue by mirror176** [phoronix-test-suite/test-profiles#173]
.\phoronix-test-suite debug-benchmark pts/renaissance
Starting the Phoronix Test Suite

         Evaluating External Test Dependencies ..........................................................................

Phoronix Test Suite v10.0.0m1

    Installed:     pts/renaissance-1.1.1

Renaissance 0.10.0:
pts/renaissance-1.1.1
Processor Test Configuration
1:  Akka Unbalanced Cobwebbed Tree             [Runs the Unbalanced Cobwebbed Tree actor workload in Akka.]
2:  Savina Reactors.IO                         [Runs benchmarks inspired by the Savina microbenchmark workloads in a sequence on Reactors.IO.]
3:  Apache Spark ALS                           [Runs the ALS algorithm from the Spark MLlib.]
4:  Random Forest                              [Runs the Random Forest algorithm from Spark MLlib.]
5:  Apache Spark Bayes                         [Runs the multinomial naive Bayes algorithm from the Spark MLlib.]
6:  Apache Spark PageRank                      [Runs a number of PageRank iterations, using RDDs.]
7:  In-Memory Database Shootout                [Executes a shootout test using several in-memory databases.]
8:  Scala Dotty                                [Runs the Random Forest algorithm from Spark MLlib.]
9:  Twitter HTTP Requests                      [Sends many small Finagle HTTP requests to a Finagle HTTP server and awaits response.]
10: Genetic Algorithm Using Jenetics + Futures [Runs a genetic algorithm using the Jenetics library and futures.]
11: Test All Options
** Multiple items can be selected, delimit by a comma. **
Test: 8

========================================
Phoronix Test Suite v10.0.0m1
System Information
========================================

  PROCESSOR:          Intel Core i7-3820 @ 3.60GHz
    Core Count:       4
    Thread Count:     8
    Cache Size:       256 MB
    Core Family:      Sandy Bridge

  GRAPHICS:           NVIDIA GeForce GTX 660 2GB
    Display Driver:   456.38 (27.21.14.5638)
    Screen:           1920x1080

  MOTHERBOARD:        ASUS SABERTOOTH X79
    BIOS Version:     4801
    Network:          AnchorFree TAP-Windows V9 + VirtualBox Host-Only

  MEMORY:             4 x 8192 MB 1333MHz F3-12800CL10-8GBZ

  DISK:               1863GB WDC WD2003FZEX-00Z4SA0
                      + 466GB Samsung SSD 850 EVO 500GB
                      + 466GB Samsung Portable SSD T3 USB
    File-System:      NTFS

  OPERATING SYSTEM:   Microsoft Windows 10 Pro Build 19041
    Kernel:           10.0 (x86_64)
    Compiler:         GCC 8.1.0 + Clang 10.0.0
    Security:         __user pointer sanitization: Disabled
                      + Retpoline: Full
                      + IBPB: Always
                      + IBRS: Enabled
                      + STIBP: Enabled
                      + KPTI Enabled: Yes
                      + PTE Inversion: Yes

========================================
Renaissance (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/renaissance-1.1.1\ && ./renaissance dotty 2>&1

====== dotty (scala-dotty), iteration 0 started ======
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/Bomarc/.phoronix-test-suite/installed-tests/pts/renaissance-1.1.1/./tmp-jars-3044322459737578936/cp-scala-dotty_2.12-0.10.0.jar7389950026018404349.jar while compiling target\dotty\src\collections.scala
Exception occurred in org.renaissance.scala.dotty.Dotty@52815fa3: Illegal char <:> at index 4: file:/C:/Users/Bomarc/.phoronix-test-suite/installed-tests/pts/renaissance-1.1.1/./tmp-jars-3044322459737578936/cp-scala-dotty_2.12-0.10.0.jar7389950026018404349.jar
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/Bomarc/.phoronix-test-suite/installed-tests/pts/renaissance-1.1.1/./tmp-jars-3044322459737578936/cp-scala-dotty_2.12-0.10.0.jar7389950026018404349.jar
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at dotty.tools.io.Directory$.apply(Directory.scala:30)
        at dotty.tools.io.AbstractFile$.getDirectory(AbstractFile.scala:25)
        at dotty.tools.dotc.classpath.ClassPathFactory.classesInPathImpl$$anonfun$1(ClassPathFactory.scala:57)
        at scala.collection.immutable.List.flatMap(List.scala:338)
        at dotty.tools.dotc.classpath.ClassPathFactory.classesInPathImpl(ClassPathFactory.scala:59)
        at dotty.tools.dotc.classpath.ClassPathFactory.classesInExpandedPath(ClassPathFactory.scala:43)
        at dotty.tools.dotc.config.PathResolver$Calculated$.basis(PathResolver.scala:234)
        at dotty.tools.dotc.config.PathResolver$Calculated$.containers(PathResolver.scala:238)
        at dotty.tools.dotc.config.PathResolver.containers(PathResolver.scala:261)
        at dotty.tools.dotc.config.PathResolver.result(PathResolver.scala:264)
        at dotty.tools.dotc.config.JavaPlatform.classPath(JavaPlatform.scala:18)
        at dotty.tools.dotc.config.JavaPlatform.rootLoader(JavaPlatform.scala:38)
        at dotty.tools.dotc.core.Contexts$ContextBase.rootLoader(Contexts.scala:603)
        at dotty.tools.dotc.core.Definitions.RootClass$$anonfun$1(Definitions.scala:187)
        at dotty.tools.dotc.core.Symbols.newModuleSymbol(Symbols.scala:156)
        at dotty.tools.dotc.core.Symbols.newPackageSymbol(Symbols.scala:196)
        at dotty.tools.dotc.core.Definitions.RootClass(Definitions.scala:187)
        at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1337)
        at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$1(Denotations.scala:1341)
        at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:1343)
        at dotty.tools.dotc.core.Symbols.requiredPackage(Symbols.scala:368)
        at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageVal(Definitions.scala:233)
        at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageClass(Definitions.scala:234)
        at dotty.tools.dotc.core.Definitions.init(Definitions.scala:1295)
        at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:616)
        at dotty.tools.dotc.core.Contexts$Context.initialize(Contexts.scala:460)
        at dotty.tools.dotc.Run.rootContext(Run.scala:43)
        at dotty.tools.dotc.Run.<init>(Run.scala:64)
        at dotty.tools.dotc.Compiler.newRun(Compiler.scala:134)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:32)
        at dotty.tools.dotc.Driver.process(Driver.scala:166)
        at dotty.tools.dotc.Driver.process(Driver.scala:135)
        at dotty.tools.dotc.Driver.process(Driver.scala:147)
        at dotty.tools.dotc.Main.process(Main.scala)
        at org.renaissance.scala.dotty.Dotty.$anonfun$runIteration$2(Dotty.scala:93)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.renaissance.scala.dotty.Dotty.runIteration(Dotty.scala:93)
        at org.renaissance.RenaissanceBenchmark.runIterationWithBeforeAndAfter(RenaissanceBenchmark.java:130)
        at org.renaissance.FixedIterationsPolicy.execute(FixedIterationsPolicy.java:48)
        at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:91)
        at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:298)
        at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:296)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:296)
        at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.renaissance.Launcher.main(Launcher.java:21)
The following benchmarks failed: dotty

The test quit with a non-zero exit status.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\renaissance-1.1.1\renaissance-1.1.1-1601574291-1.log

The following tests failed to properly run:

    - pts/renaissance-1.1.1: Test: Scala Dotty

**Comment by michaellarabel** [comment]
This is known to fail on Windows, it's an upstream OpenJDK or Renaissance bug. Thanks though for reporting.
