### ISSUE TITLE
pts/hbase-1.0.1 failed to execute due to invalid java version 

### ISSUE THREAD

**Issue by intelmy** [phoronix-test-suite/test-profiles#247]
when running hbase-1.0.1, it reports error as below:

        at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2940)
Caused by: java.lang.IllegalArgumentException: **Invalid Java version 11.0.16.1**
        at org.eclipse.jetty.util.JavaVersion.parseJDK9(JavaVersion.java:71)
        at org.eclipse.jetty.util.JavaVersion.parse(JavaVersion.java:49)
        at org.eclipse.jetty.util.JavaVersion.<clinit>(JavaVersion.java:43)

seems the jetty used in this hbase is not compatible with the new java version naming rule (have 4 numbers instead of 3). 

Any suggestion on this

**Comment by intelmy** [comment]
Thanks Michael for your quick response 👍
